#!/usr/bin/env bash

# default value, change if you want or just delete this line
# for this to just work, if you have mpd this is likely
# already set
MPD_PORT=6600

# sends command to mpd
function cmd() {
  # ncless is a miniscule c program
  # that just sends a message over
  # tcp, use it if you don't want
  # to add a dependency
  printf "$1\n" | ./ncless localhost "$MPD_PORT"

  # netcat is a lot more robust and
  # useful as a program, use it if
  # you already have it
  # printf "$1\n" | nc localhost "$MPD_PORT" -q 0  
}

# formats mpd output
function format() {
  printf "MPD: $1"
}

# prints the output of mpd
# boring style
# printf "$(format "$(cmd $1)")\n"

# sends the output of mpd to your
# tmux status bar for 1 second
# doesn't work with newlines I think
tmux display-message -d 1000 "$(format "$(cmd $1)")"

# sends the output of mpd to
# your notification daemon
# notify-send "$(format "$(cmd $1)")"
