#!/usr/bin/env sh

# this script opens up a menu of options and when you select one
# it sends a command to mpd thorugh the mpdcmd script

# you can use programs other than fzy with this pretty easily, but if 
# you do be prepared to patch things

case "$(printf "pause\nnext\nprevious\nsong\nraw\nqafter\nqend" | fzy)" in

  pause) mpdcmd pause ;;

  next) mpdcmd next ;;

  previous) mpdcmd previous ;;

  song) read -p "> " song ;
    # cursor up and carriage return
    printf "\033[A\r" ; 
    mpdcmd "song "$song ;;

  raw) read -p "> " rawcmd ; 
    # cursor up and carriage return
    printf "\033[A\r" ; 
    mpdcmd $rawcmd ;; 

  qafter) find $HOME/Music -type f | fzy | sed 's/^/add +0 /' | xargs mpdcmd ;;

  qend) find $HOME/Music -type f | fzy | sed 's/^/add +100 /' | xargs mpdcmd ;;

  *) exit 1 ;;

esac
