#!/usr/bin/env sh

case "$(printf "pause\nnext\nprevious\nsong\nraw\nqafter\nqend" | fzy)" in
  pause) ./mpdcmd pause ;;
  next) ./mpdcmd next ;;
  previous) ./mpdcmd previous ;;
  song) ./mpdcmd song ;;
  raw) read -p "> " rawcmd; 
    # escape sequence moves cursor up one line and prints a carriage return
    # needed to overwrite rawcmd prompt, doesn't get sent to mpd
    printf "\033[A\r";
    ./mpdcmd $rawcmd ;; 
  qafter) find $HOME/Music -type f | fzy | awk '{print "add +0", $0}' | ./mpdcmd ;;
  qend) ;;
  *) exit 1 ;;
esac
